export { default as vueTemplate } from './vue.sample?raw'
export { default as jsonTemplate } from './json.sample?raw'
export { default as tomlTemplate } from './toml.sample?raw'
export { default as yamlTemplate } from './yaml.sample?raw'
export { default as astroTemplate } from './astro.sample?raw'
export { default as svelteTemplate } from './svelte.sample?raw'
export { default as javascriptTemplate } from './javascript.sample?raw'
export { default as typescriptTemplate } from './typescript.sample?raw'
